#!/usr/bin/env bash
# Display Best School 9 times and hi best school the 10th time

i=0
while [ $i -lt 10 ]
do
    if [ $i == 8 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    i=$((i+1))
done

