#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59

hours=0
minutes=0

while [ $hours -le 12 ]; do
    echo "Hour: $hours"
    while [ $minutes -lt 60 ]; do
        echo $((minutes))
        minutes=$((minutes+1))
    done
    minutes=0
    hours=$((hours+1))
done

