#!/usr/bin/env bash
#displays the content of the current directory#In a list format with only the part of the name after the first dash being displayed

for file in *; do
    name=${file##*-}
    echo $name
done

