#!/usr/bin/env bash
#Checks if school file exists, empty or is a regular file

# check if the file exists
if [ -e "school" ]; then
  echo "school file exists"
  # check if the file is empty
  if [ ! -s "school" ]; then
    echo "school file is empty"
  else
    echo "school file is not empty"
  fi
  # check if the file is a regular file
  if [ -f "school" ]; then
    echo "school is a regular file"
  else
    echo "school is not a regular file"
  fi
else
  echo "school file does not exist"
fi

