#!/usr/bin/env bash
#Setupa broken container so that it works with nginx on port 8080
pkill apache2
sed -i 's/user www-data/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/g'/etc/nginx/nginx.conf
nginx -t
sudo -u nginx service nginx restart
